file_server:
  # uvicorn服务运行的host和port
  host: "0.0.0.0"
  port: 8080

  # 数据目录，不存在会自动创建
  data_path: "data"
  # 日志目录，不存在会自动创建
  log_path: "logs"
  # 日志保留天数
  log_reserve_days: 15
  # 日志级别，0-debug,1-info,2-warning,3-error,4-critical
  log_level: 1

  # 在没有数据文件的时候，初始化系统的管理员账户以及密码
  init_admin:
    username: root
    password: 123456
